### ISSUE TITLE
Testing and env switch

### ISSUE THREAD

**Issue by eventomer** [vangelov/Injineer#2]
From what I understand about DI it should make it easier to test the code and switch envs easily. how does this framework helps achieve this goal?

**Comment by vangelov** [comment]
Your understanding is correct. The framework helps you achieve that by decoupling your objects from their dependencies. Every instance that you need, you get it from the container. You can either configure the container differently for each environment, or you can have a separate container for each environment. You can also have a separate container for your testing, or you can just inject dependencies manually if you want. By having no singletons you are free to configure your object graph dynamically thus being able to have different environments.

For example let's say you have an universal app where your view controllers depend on a configuration object which is different for tablets and phones:

``` Objective-c
@interface ProductsListViewController

@property (nonatomic, strong) AppConfig *appConfig;

@end
```

Then in you context you add the following objects in the container:

``` Objective-c
// AppContext.m:

if(IS_PAD) {
    [container addInstance: @"appConfig_tablet.plist" forName: @"appConfigFile"];
}
else {
    [container addInstance: @"appConfig_phone.plist" forName: @"appConfigFile"];
}

[container addProvider: @"appConfig" 
               options: INJProviderOptionSingleton 
          dependencies: @[ @"appConfigFile"] 
               creator: ^id(NSDictionary *values) {
                   return [[AppConfig alloc] initWithFile: values[@"appConfigFile"]];
               }];

[container addProvider: @"productsListViewController" 
               options: 0 
          dependencies: @[ @"appConfig"] 
               creator: ^id(NSDictionary *values) {
                   return [[ProductsListViewController alloc] initWithAppConfig: values[@"appConfig"]];
               }];
```

In your unit tests you can choose to create a different container with test config data or just create the config object manually and set it in the controller you're testing.

**Comment by eventomer** [comment]
Nice! Thanks for taking the time to answer :)
